import type { NovaApp } from '@endge/nova'
import type { EventList } from '@endge/utils'

const REGISTERED_APPS = new WeakSet<NovaApp<any>>()

export const NOVA_UI_KIT_LIGHT_TOKENS = {
  '--nova-ui-text': '#172033',
  '--nova-ui-muted': '#64748b',
  '--nova-ui-subtle': '#94a3b8',
  '--nova-ui-surface': '#ffffff',
  '--nova-ui-surface-raised': '#ffffff',
  '--nova-ui-surface-muted': '#f8fafc',
  '--nova-ui-control': '#ffffff',
  '--nova-ui-control-muted': '#f1f5f9',
  '--nova-ui-control-hover': '#f8fafc',
  '--nova-ui-control-pressed': '#eef2f7',
  '--nova-ui-control-active': '#eff6ff',
  '--nova-ui-border': '#cbd5e1',
  '--nova-ui-border-muted': '#d6d9e2',
  '--nova-ui-border-strong': '#94a3b8',
  '--nova-ui-accent': '#2563eb',
  '--nova-ui-accent-hover': '#1d4ed8',
  '--nova-ui-accent-pressed': '#1e40af',
  '--nova-ui-accent-soft': '#dbeafe',
  '--nova-ui-accent-border': '#93c5fd',
  '--nova-ui-danger': '#dc2626',
  '--nova-ui-danger-hover': '#b91c1c',
  '--nova-ui-danger-pressed': '#991b1b',
  '--nova-ui-danger-soft': '#fee2e2',
  '--nova-ui-danger-border': '#fca5a5',
  '--nova-ui-success': '#047857',
  '--nova-ui-success-soft': '#ecfdf5',
  '--nova-ui-success-border': '#a7f3d0',
  '--nova-ui-warning': '#b45309',
  '--nova-ui-warning-soft': '#fffbeb',
  '--nova-ui-warning-border': '#fde68a',
  '--nova-ui-overlay': 'rgba(15,23,42,0.18)',
  '--nova-ui-overlay-strong': 'rgba(15,23,42,0.38)',
  '--nova-ui-transparent': 'rgba(255,255,255,0)',
  '--nova-ui-thumb': 'rgba(71,85,105,0.70)',
  '--nova-ui-track': 'rgba(148,163,184,0.22)',
  '--nova-ui-focus': 'rgba(37,99,235,0.22)',
  '--nova-ui-inverse-text': '#ffffff',
  '--nova-ui-inverse-surface': '#111827',
  '--nova-text-block-color': '#172033',
  '--nova-surface-background': '#ffffff',
  '--nova-surface-border-color': '#d6d9e2',
  '--nova-panel-background': '#ffffff',
  '--nova-panel-color': '#172033',
  '--nova-panel-border-color': '#cbd5e1',
  '--nova-panel-subtitle-color': '#64748b',
  '--nova-button-background': '#ffffff',
  '--nova-button-color': '#172033',
  '--nova-button-border-color': '#cbd5e1',
  '--nova-button-hover-background': '#f8fafc',
  '--nova-button-pressed-background': '#eef2f7',
  '--nova-button-active-background': '#eff6ff',
  '--nova-button-primary-background': '#2563eb',
  '--nova-button-primary-color': '#ffffff',
  '--nova-button-primary-border-color': '#1d4ed8',
  '--nova-button-primary-hover-background': '#1d4ed8',
  '--nova-button-primary-pressed-background': '#1e40af',
  '--nova-button-primary-active-background': '#1d4ed8',
  '--nova-button-danger-background': '#dc2626',
  '--nova-button-danger-color': '#ffffff',
  '--nova-button-danger-border-color': '#b91c1c',
  '--nova-button-danger-hover-background': '#b91c1c',
  '--nova-button-danger-pressed-background': '#991b1b',
  '--nova-button-ghost-background': 'rgba(255,255,255,0)',
  '--nova-button-ghost-color': '#334155',
  '--nova-button-ghost-border-color': 'rgba(148,163,184,0)',
  '--nova-button-ghost-hover-background': 'rgba(148,163,184,0.14)',
  '--nova-button-ghost-pressed-background': 'rgba(148,163,184,0.24)',
  '--nova-button-ghost-active-background': 'rgba(37,99,235,0.14)',
  '--nova-badge-background': '#f1f5f9',
  '--nova-badge-color': '#334155',
  '--nova-badge-border-color': '#cbd5e1',
  '--nova-badge-info-background': '#dbeafe',
  '--nova-badge-info-color': '#1d4ed8',
  '--nova-badge-info-border-color': '#93c5fd',
  '--nova-badge-success-background': '#dcfce7',
  '--nova-badge-success-color': '#166534',
  '--nova-badge-success-border-color': '#86efac',
  '--nova-badge-warning-background': '#fef3c7',
  '--nova-badge-warning-color': '#92400e',
  '--nova-badge-warning-border-color': '#fcd34d',
  '--nova-badge-danger-background': '#fee2e2',
  '--nova-badge-danger-color': '#991b1b',
  '--nova-badge-danger-border-color': '#fca5a5',
  '--nova-chip-background': '#f8fafc',
  '--nova-chip-color': '#334155',
  '--nova-chip-border-color': '#cbd5e1',
  '--nova-chip-hover-background': '#eef2f7',
  '--nova-chip-pressed-background': '#e2e8f0',
  '--nova-chip-selected-background': '#dbeafe',
  '--nova-chip-selected-color': '#1d4ed8',
  '--nova-chip-selected-border-color': '#60a5fa',
  '--nova-tag-background': '#f8fafc',
  '--nova-tag-color': '#475569',
  '--nova-tag-border-color': '#cbd5e1',
  '--nova-tag-info-background': '#eff6ff',
  '--nova-tag-info-color': '#1d4ed8',
  '--nova-tag-info-border-color': '#bfdbfe',
  '--nova-tag-success-background': '#ecfdf5',
  '--nova-tag-success-color': '#047857',
  '--nova-tag-success-border-color': '#a7f3d0',
  '--nova-tag-warning-background': '#fffbeb',
  '--nova-tag-warning-color': '#b45309',
  '--nova-tag-warning-border-color': '#fde68a',
  '--nova-tag-danger-background': '#fef2f2',
  '--nova-tag-danger-color': '#b91c1c',
  '--nova-tag-danger-border-color': '#fecaca',
  '--nova-tag-selected-color': '#ffffff',
  '--nova-input-background': '#ffffff',
  '--nova-input-filled-background': '#f1f5f9',
  '--nova-input-ghost-background': 'rgba(255,255,255,0)',
  '--nova-input-underline-background': 'rgba(255,255,255,0)',
  '--nova-input-color': '#172033',
  '--nova-input-border-color': '#cbd5e1',
  '--nova-input-ghost-border-color': 'rgba(148,163,184,0)',
  '--nova-input-hover-background': '#f8fafc',
  '--nova-input-pressed-background': '#eef2ff',
  '--nova-input-ghost-hover-background': 'rgba(148,163,184,0.12)',
  '--nova-input-selection-color': 'rgba(37, 99, 235, 0.22)',
  '--nova-input-caret-color': '#2563eb',
  '--nova-input-placeholder-color': '#94a3b8',
  '--nova-input-focus-border-color': '#2563eb',
  '--nova-input-error-color': '#dc2626',
  '--nova-input-label-color': '#475569',
  '--nova-input-affix-color': '#64748b',
  '--nova-input-hint-color': '#64748b',
  '--nova-input-menu-background': '#ffffff',
  '--nova-input-menu-border-color': '#cbd5e1',
  '--nova-input-menu-active-background': '#eff6ff',
  '--nova-checkbox-background': '#ffffff',
  '--nova-checkbox-color': '#172033',
  '--nova-checkbox-border-color': '#cbd5e1',
  '--nova-checkbox-accent-color': '#2563eb',
  '--nova-checkbox-hover-background': '#f8fafc',
  '--nova-checkbox-pressed-background': '#eff6ff',
  '--nova-toggle-color': '#172033',
  '--nova-toggle-accent-color': '#2563eb',
  '--nova-toggle-track-color': '#cbd5e1',
  '--nova-toggle-thumb-color': '#ffffff',
  '--nova-toggle-border-color': '#cbd5e1',
  '--nova-toggle-thumb-border-color': 'rgba(15,23,42,0.12)',
  '--nova-slider-accent-color': '#2563eb',
  '--nova-slider-track-color': '#dbe4ef',
  '--nova-slider-thumb-color': '#ffffff',
  '--nova-slider-thumb-border-color': '#2563eb',
  '--nova-segmented-control-background': '#f1f5f9',
  '--nova-segmented-control-color': '#334155',
  '--nova-segmented-control-border-color': '#cbd5e1',
  '--nova-segmented-control-active-background': '#ffffff',
  '--nova-segmented-control-accent-color': '#2563eb',
  '--nova-scroll-area-background': '#ffffff',
  '--nova-scroll-area-border-color': '#d6d9e2',
  '--nova-scroll-area-track-color': 'rgba(148,163,184,0.22)',
  '--nova-scroll-area-thumb-color': 'rgba(71,85,105,0.70)',
  '--nova-scrollbar-track-color': 'rgba(148,163,184,0.24)',
  '--nova-scrollbar-thumb-color': 'rgba(71,85,105,0.72)',
  '--nova-scrollbar-thumb-hover-color': 'rgba(71,85,105,0.88)',
  '--nova-split-pane-background': '#ffffff',
  '--nova-split-pane-border-color': '#cbd5e1',
  '--nova-split-pane-resizer-color': '#94a3b8',
  '--nova-split-pane-resizer-overlay-color': 'rgba(37,99,235,0.14)',
  '--nova-image-background': 'rgba(148, 163, 184, 0.18)',
  '--nova-image-border-color': 'rgba(15,23,42,0.10)',
  '--nova-overlay-background': '#ffffff',
  '--nova-overlay-color': '#172033',
  '--nova-overlay-border-color': '#cbd5e1',
  '--nova-overlay-backdrop-background': 'rgba(15,23,42,0.18)',
  '--nova-dialog-background': '#ffffff',
  '--nova-dialog-color': '#172033',
  '--nova-dialog-border-color': '#cbd5e1',
  '--nova-dialog-backdrop-background': 'rgba(15,23,42,0.38)',
  '--nova-dialog-description-color': '#64748b',
  '--nova-dialog-handle-background': 'rgba(148,163,184,0.42)',
  '--nova-dialog-resize-background': 'rgba(100,116,139,0.45)',
  '--nova-popover-background': '#ffffff',
  '--nova-popover-color': '#172033',
  '--nova-popover-border-color': '#cbd5e1',
  '--nova-popover-arrow-background': '#ffffff',
  '--nova-popover-backdrop-background': 'rgba(15,23,42,0.18)',
  '--nova-tooltip-background': '#111827',
  '--nova-tooltip-color': '#ffffff',
  '--nova-tooltip-border-color': 'rgba(255,255,255,0.12)',
  '--nova-action-list-background': '#ffffff',
  '--nova-action-list-color': '#172033',
  '--nova-action-list-border-color': '#cbd5e1',
  '--nova-action-list-active-background': '#eff6ff',
  '--nova-action-list-separator-color': '#e2e8f0',
  '--nova-action-list-group-color': '#64748b',
  '--nova-action-list-disabled-color': '#94a3b8',
  '--nova-action-list-danger-color': '#dc2626',
  '--nova-action-list-description-color': '#64748b',
  '--nova-action-list-shortcut-color': '#94a3b8',
  '--nova-action-list-submenu-color': '#64748b',
  '--nova-toast-background': '#ffffff',
  '--nova-toast-color': '#172033',
  '--nova-toast-border-color': '#cbd5e1',
  '--nova-toast-message-color': '#64748b',
  '--nova-toast-action-color': '#2563eb',
  '--nova-toast-progress-background': '#2563eb',
  '--nova-toast-info-background': '#eff6ff',
  '--nova-toast-info-color': '#1d4ed8',
  '--nova-toast-info-border-color': '#bfdbfe',
  '--nova-toast-success-background': '#ecfdf5',
  '--nova-toast-success-color': '#047857',
  '--nova-toast-success-border-color': '#bbf7d0',
  '--nova-toast-warning-background': '#fffbeb',
  '--nova-toast-warning-color': '#b45309',
  '--nova-toast-warning-border-color': '#fde68a',
  '--nova-toast-danger-background': '#fef2f2',
  '--nova-toast-danger-color': '#b91c1c',
  '--nova-toast-danger-border-color': '#fecaca',
  '--nova-zoom-controls-background': '#ffffff',
  '--nova-zoom-controls-color': '#172033',
  '--nova-zoom-controls-value-color': '#344054',
  '--nova-zoom-controls-border-color': '#cbd5e1',
  '--nova-zoom-controls-button-hover-background': '#f8fafc',
  '--nova-zoom-controls-button-pressed-background': '#eef2f7',
  '--nova-fps-meter-background': 'rgba(17,24,39,0.82)',
  '--nova-fps-meter-minimal-background': 'rgba(17,24,39,0.66)',
  '--nova-fps-meter-border-color': 'rgba(255,255,255,0.14)',
  '--nova-fps-meter-color': '#ffffff',
} as const

export const NOVA_UI_KIT_DARK_TOKENS = {
  '--nova-ui-text': '#e5edf6',
  '--nova-ui-muted': '#9aa8b8',
  '--nova-ui-subtle': '#718197',
  '--nova-ui-surface': '#111827',
  '--nova-ui-surface-raised': '#172033',
  '--nova-ui-surface-muted': '#1f2937',
  '--nova-ui-control': '#172033',
  '--nova-ui-control-muted': '#1f2937',
  '--nova-ui-control-hover': '#243044',
  '--nova-ui-control-pressed': '#2d3a50',
  '--nova-ui-control-active': '#1e3a5f',
  '--nova-ui-border': '#334155',
  '--nova-ui-border-muted': '#263449',
  '--nova-ui-border-strong': '#475569',
  '--nova-ui-accent': '#60a5fa',
  '--nova-ui-accent-hover': '#93c5fd',
  '--nova-ui-accent-pressed': '#bfdbfe',
  '--nova-ui-accent-soft': '#17375e',
  '--nova-ui-accent-border': '#2563eb',
  '--nova-ui-danger': '#f87171',
  '--nova-ui-danger-hover': '#fca5a5',
  '--nova-ui-danger-pressed': '#fecaca',
  '--nova-ui-danger-soft': '#4a1d24',
  '--nova-ui-danger-border': '#7f1d1d',
  '--nova-ui-success': '#34d399',
  '--nova-ui-success-soft': '#123d32',
  '--nova-ui-success-border': '#047857',
  '--nova-ui-warning': '#fbbf24',
  '--nova-ui-warning-soft': '#3f2e12',
  '--nova-ui-warning-border': '#92400e',
  '--nova-ui-overlay': 'rgba(2,6,23,0.42)',
  '--nova-ui-overlay-strong': 'rgba(2,6,23,0.62)',
  '--nova-ui-transparent': 'rgba(255,255,255,0)',
  '--nova-ui-thumb': 'rgba(148,163,184,0.70)',
  '--nova-ui-track': 'rgba(71,85,105,0.30)',
  '--nova-ui-focus': 'rgba(96,165,250,0.26)',
  '--nova-ui-inverse-text': '#0f172a',
  '--nova-ui-inverse-surface': '#f8fafc',
  '--nova-text-block-color': '#e5edf6',
  '--nova-surface-background': '#111827',
  '--nova-surface-border-color': '#263449',
  '--nova-panel-background': '#111827',
  '--nova-panel-color': '#e5edf6',
  '--nova-panel-border-color': '#334155',
  '--nova-panel-subtitle-color': '#9aa8b8',
  '--nova-button-background': '#172033',
  '--nova-button-color': '#e5edf6',
  '--nova-button-border-color': '#334155',
  '--nova-button-hover-background': '#243044',
  '--nova-button-pressed-background': '#2d3a50',
  '--nova-button-active-background': '#1e3a5f',
  '--nova-button-primary-background': '#3b82f6',
  '--nova-button-primary-color': '#ffffff',
  '--nova-button-primary-border-color': '#2563eb',
  '--nova-button-primary-hover-background': '#60a5fa',
  '--nova-button-primary-pressed-background': '#93c5fd',
  '--nova-button-primary-active-background': '#2563eb',
  '--nova-button-danger-background': '#dc2626',
  '--nova-button-danger-color': '#ffffff',
  '--nova-button-danger-border-color': '#991b1b',
  '--nova-button-danger-hover-background': '#ef4444',
  '--nova-button-danger-pressed-background': '#f87171',
  '--nova-button-ghost-background': 'rgba(255,255,255,0)',
  '--nova-button-ghost-color': '#d7e2ec',
  '--nova-button-ghost-border-color': 'rgba(148,163,184,0)',
  '--nova-button-ghost-hover-background': 'rgba(148,163,184,0.14)',
  '--nova-button-ghost-pressed-background': 'rgba(148,163,184,0.24)',
  '--nova-button-ghost-active-background': 'rgba(96,165,250,0.18)',
  '--nova-badge-background': '#1f2937',
  '--nova-badge-color': '#cbd5e1',
  '--nova-badge-border-color': '#334155',
  '--nova-badge-info-background': '#17375e',
  '--nova-badge-info-color': '#93c5fd',
  '--nova-badge-info-border-color': '#2563eb',
  '--nova-badge-success-background': '#123d32',
  '--nova-badge-success-color': '#86efac',
  '--nova-badge-success-border-color': '#047857',
  '--nova-badge-warning-background': '#3f2e12',
  '--nova-badge-warning-color': '#fbbf24',
  '--nova-badge-warning-border-color': '#92400e',
  '--nova-badge-danger-background': '#4a1d24',
  '--nova-badge-danger-color': '#fca5a5',
  '--nova-badge-danger-border-color': '#7f1d1d',
  '--nova-chip-background': '#1f2937',
  '--nova-chip-color': '#cbd5e1',
  '--nova-chip-border-color': '#334155',
  '--nova-chip-hover-background': '#243044',
  '--nova-chip-pressed-background': '#2d3a50',
  '--nova-chip-selected-background': '#17375e',
  '--nova-chip-selected-color': '#93c5fd',
  '--nova-chip-selected-border-color': '#2563eb',
  '--nova-tag-background': '#1f2937',
  '--nova-tag-color': '#cbd5e1',
  '--nova-tag-border-color': '#334155',
  '--nova-tag-info-background': '#17375e',
  '--nova-tag-info-color': '#93c5fd',
  '--nova-tag-info-border-color': '#2563eb',
  '--nova-tag-success-background': '#123d32',
  '--nova-tag-success-color': '#86efac',
  '--nova-tag-success-border-color': '#047857',
  '--nova-tag-warning-background': '#3f2e12',
  '--nova-tag-warning-color': '#fbbf24',
  '--nova-tag-warning-border-color': '#92400e',
  '--nova-tag-danger-background': '#4a1d24',
  '--nova-tag-danger-color': '#fca5a5',
  '--nova-tag-danger-border-color': '#7f1d1d',
  '--nova-tag-selected-color': '#ffffff',
  '--nova-input-background': '#172033',
  '--nova-input-filled-background': '#1f2937',
  '--nova-input-ghost-background': 'rgba(255,255,255,0)',
  '--nova-input-underline-background': 'rgba(255,255,255,0)',
  '--nova-input-color': '#e5edf6',
  '--nova-input-border-color': '#334155',
  '--nova-input-ghost-border-color': 'rgba(148,163,184,0)',
  '--nova-input-hover-background': '#243044',
  '--nova-input-pressed-background': '#1e3a5f',
  '--nova-input-ghost-hover-background': 'rgba(148,163,184,0.12)',
  '--nova-input-selection-color': 'rgba(96,165,250,0.26)',
  '--nova-input-caret-color': '#60a5fa',
  '--nova-input-placeholder-color': '#718197',
  '--nova-input-focus-border-color': '#60a5fa',
  '--nova-input-error-color': '#f87171',
  '--nova-input-label-color': '#9aa8b8',
  '--nova-input-affix-color': '#9aa8b8',
  '--nova-input-hint-color': '#9aa8b8',
  '--nova-input-menu-background': '#111827',
  '--nova-input-menu-border-color': '#334155',
  '--nova-input-menu-active-background': '#1e3a5f',
  '--nova-checkbox-background': '#172033',
  '--nova-checkbox-color': '#e5edf6',
  '--nova-checkbox-border-color': '#334155',
  '--nova-checkbox-accent-color': '#60a5fa',
  '--nova-checkbox-hover-background': '#243044',
  '--nova-checkbox-pressed-background': '#1e3a5f',
  '--nova-toggle-color': '#e5edf6',
  '--nova-toggle-accent-color': '#60a5fa',
  '--nova-toggle-track-color': '#334155',
  '--nova-toggle-thumb-color': '#e5edf6',
  '--nova-toggle-border-color': '#334155',
  '--nova-toggle-thumb-border-color': 'rgba(2,6,23,0.32)',
  '--nova-slider-accent-color': '#60a5fa',
  '--nova-slider-track-color': '#334155',
  '--nova-slider-thumb-color': '#e5edf6',
  '--nova-slider-thumb-border-color': '#60a5fa',
  '--nova-segmented-control-background': '#1f2937',
  '--nova-segmented-control-color': '#cbd5e1',
  '--nova-segmented-control-border-color': '#334155',
  '--nova-segmented-control-active-background': '#172033',
  '--nova-segmented-control-accent-color': '#60a5fa',
  '--nova-scroll-area-background': '#111827',
  '--nova-scroll-area-border-color': '#263449',
  '--nova-scroll-area-track-color': 'rgba(71,85,105,0.30)',
  '--nova-scroll-area-thumb-color': 'rgba(148,163,184,0.70)',
  '--nova-scrollbar-track-color': 'rgba(71,85,105,0.30)',
  '--nova-scrollbar-thumb-color': 'rgba(148,163,184,0.72)',
  '--nova-scrollbar-thumb-hover-color': 'rgba(203,213,225,0.88)',
  '--nova-split-pane-background': '#111827',
  '--nova-split-pane-border-color': '#334155',
  '--nova-split-pane-resizer-color': '#718197',
  '--nova-split-pane-resizer-overlay-color': 'rgba(96,165,250,0.18)',
  '--nova-image-background': 'rgba(148,163,184,0.16)',
  '--nova-image-border-color': 'rgba(226,232,240,0.12)',
  '--nova-overlay-background': '#111827',
  '--nova-overlay-color': '#e5edf6',
  '--nova-overlay-border-color': '#334155',
  '--nova-overlay-backdrop-background': 'rgba(2,6,23,0.42)',
  '--nova-dialog-background': '#111827',
  '--nova-dialog-color': '#e5edf6',
  '--nova-dialog-border-color': '#334155',
  '--nova-dialog-backdrop-background': 'rgba(2,6,23,0.62)',
  '--nova-dialog-description-color': '#9aa8b8',
  '--nova-dialog-handle-background': 'rgba(148,163,184,0.36)',
  '--nova-dialog-resize-background': 'rgba(148,163,184,0.38)',
  '--nova-popover-background': '#111827',
  '--nova-popover-color': '#e5edf6',
  '--nova-popover-border-color': '#334155',
  '--nova-popover-arrow-background': '#111827',
  '--nova-popover-backdrop-background': 'rgba(2,6,23,0.42)',
  '--nova-tooltip-background': '#e5edf6',
  '--nova-tooltip-color': '#0f172a',
  '--nova-tooltip-border-color': 'rgba(15,23,42,0.14)',
  '--nova-action-list-background': '#111827',
  '--nova-action-list-color': '#e5edf6',
  '--nova-action-list-border-color': '#334155',
  '--nova-action-list-active-background': '#1e3a5f',
  '--nova-action-list-separator-color': '#263449',
  '--nova-action-list-group-color': '#9aa8b8',
  '--nova-action-list-disabled-color': '#718197',
  '--nova-action-list-danger-color': '#f87171',
  '--nova-action-list-description-color': '#9aa8b8',
  '--nova-action-list-shortcut-color': '#718197',
  '--nova-action-list-submenu-color': '#9aa8b8',
  '--nova-toast-background': '#111827',
  '--nova-toast-color': '#e5edf6',
  '--nova-toast-border-color': '#334155',
  '--nova-toast-message-color': '#9aa8b8',
  '--nova-toast-action-color': '#60a5fa',
  '--nova-toast-progress-background': '#60a5fa',
  '--nova-toast-info-background': '#17375e',
  '--nova-toast-info-color': '#93c5fd',
  '--nova-toast-info-border-color': '#2563eb',
  '--nova-toast-success-background': '#123d32',
  '--nova-toast-success-color': '#86efac',
  '--nova-toast-success-border-color': '#047857',
  '--nova-toast-warning-background': '#3f2e12',
  '--nova-toast-warning-color': '#fbbf24',
  '--nova-toast-warning-border-color': '#92400e',
  '--nova-toast-danger-background': '#4a1d24',
  '--nova-toast-danger-color': '#fca5a5',
  '--nova-toast-danger-border-color': '#7f1d1d',
  '--nova-zoom-controls-background': '#111827',
  '--nova-zoom-controls-color': '#e5edf6',
  '--nova-zoom-controls-value-color': '#b6c3cf',
  '--nova-zoom-controls-border-color': '#334155',
  '--nova-zoom-controls-button-hover-background': '#1f2937',
  '--nova-zoom-controls-button-pressed-background': '#293548',
  '--nova-fps-meter-background': 'rgba(226,232,240,0.92)',
  '--nova-fps-meter-minimal-background': 'rgba(226,232,240,0.78)',
  '--nova-fps-meter-border-color': 'rgba(15,23,42,0.14)',
  '--nova-fps-meter-color': '#0f172a',
} as const

export function ensureNovaUIKitThemes<E extends EventList>(app: NovaApp<E>): void {
  if (REGISTERED_APPS.has(app)) return
  REGISTERED_APPS.add(app)
  const active = app.theme.active()
  if (active) return
  app.theme.register({
    id: 'light',
    title: 'Light',
    tokens: { ...NOVA_UI_KIT_LIGHT_TOKENS },
  }, { activate: !active })
  app.theme.register({
    id: 'dark',
    title: 'Dark',
    tokens: { ...NOVA_UI_KIT_DARK_TOKENS },
  })
}

export function resolveNovaUiThemeValue<E extends EventList>(
  app: NovaApp<E>,
  value: string | undefined,
): string | undefined {
  if (!value || !value.includes('var(')) return value
  let result = ''
  let cursor = 0

  while (cursor < value.length) {
    const start = value.indexOf('var(', cursor)
    if (start < 0) {
      result += value.slice(cursor)
      break
    }

    const end = findMatchingParen(value, start + 3)
    if (end < 0) {
      result += value.slice(cursor)
      break
    }

    result += value.slice(cursor, start)
    const body = value.slice(start + 4, end)
    const comma = findTopLevelComma(body)
    const name = (comma < 0 ? body : body.slice(0, comma)).trim()
    const fallback = comma < 0 ? undefined : body.slice(comma + 1).trim()
    result += app.theme.resolve(name, fallback) ?? fallback ?? ''
    cursor = end + 1
  }

  return result
}

function findMatchingParen(source: string, openIndex: number): number {
  let depth = 0
  for (let index = openIndex; index < source.length; index += 1) {
    const char = source[index]
    if (char === '(') depth += 1
    else if (char === ')') {
      depth -= 1
      if (depth === 0) return index
    }
  }
  return -1
}

function findTopLevelComma(source: string): number {
  let depth = 0
  for (let index = 0; index < source.length; index += 1) {
    const char = source[index]
    if (char === '(') depth += 1
    else if (char === ')') depth = Math.max(0, depth - 1)
    else if (char === ',' && depth === 0) return index
  }
  return -1
}
