export * from '@/components/TextBlock/TextBlock'
export * from '@/components/TextBlock/TextBlock.config'
export * from '@/components/TextBlock/TextBlock.registry'
export * from '@/components/TextBlock/TextBlock.schema'
export * from '@/components/TextBlock/types'
