import type { NovaComponentCreateContext, NovaComponentDescriptor, NovaComponentNode, NovaComponentSchema } from '@endge/nova'
import type { EventList } from '@endge/utils'
import { NOVA_UI_COMMON_DIRTY_POLICY, NOVA_UI_COMMON_FIELD_DEFINITIONS, commonMeasureBounds, normalizeCommonProps, sizeTokenHeight } from '@/shared/component'
import { CHIP_SCHEMA_TYPE, type ChipApi, type ChipProps, type ChipResolvedProps } from '@/components/Chip/chip.types'

export type ChipDescriptor = NovaComponentDescriptor<ChipResolvedProps, ChipApi, Record<string, never>, ChipProps>
export type ChipNodeFactory = <E extends EventList>(context: NovaComponentCreateContext<E>, schema: NovaComponentSchema<ChipProps>) => NovaComponentNode<ChipResolvedProps, ChipApi, Record<string, never>, ChipProps, E>
export const CHIP_FIELD_DEFINITIONS = { ...NOVA_UI_COMMON_FIELD_DEFINITIONS, label: { type: 'string' }, icon: { type: 'icon' }, avatar: { type: 'icon' }, selected: { type: 'boolean' }, removable: { type: 'boolean' }, tone: { type: 'string' }, size: { type: 'string' }, parts: { type: 'record' }, onPress: { type: 'function' }, onRemove: { type: 'function' } } as const
export function normalizeChipProps(props: ChipProps = {}): ChipResolvedProps { const selected = props.selected ?? false; return { ...normalizeCommonProps(props, { width: 112, height: sizeTokenHeight(props.size ?? 'md', 30), background: selected ? 'var(--nova-chip-selected-background, #dbeafe)' : 'var(--nova-chip-background, #f8fafc)', color: selected ? 'var(--nova-chip-selected-color, #1d4ed8)' : 'var(--nova-chip-color, #334155)', border: { color: selected ? 'var(--nova-chip-selected-border-color, #60a5fa)' : 'var(--nova-chip-border-color, #cbd5e1)', width: 1, radius: 999 }, padding: { horizontal: 10, vertical: 4 }, hoverBackground: 'var(--nova-chip-hover-background, #eef2f7)', pressedBackground: 'var(--nova-chip-pressed-background, #e2e8f0)', cursor: { hover: 'pointer', pressed: 'pointer', disabled: 'not-allowed' } }), label: props.label ?? '', icon: props.icon, avatar: props.avatar, selected, removable: props.removable ?? false, tone: props.tone ?? 'neutral', size: props.size ?? 'md', parts: props.parts, onPress: props.onPress, onRemove: props.onRemove } }
export function createChipDescriptor(createNode?: ChipNodeFactory): ChipDescriptor { const descriptor: ChipDescriptor = { type: CHIP_SCHEMA_TYPE, name: 'Chip', title: 'Chip', version: '0.1.0', kind: 'node-component', dirtyPolicy: { matrix: NOVA_UI_COMMON_DIRTY_POLICY.matrix, update: [...NOVA_UI_COMMON_DIRTY_POLICY.update, 'label', 'icon', 'avatar', 'removable', 'size'], render: [...NOVA_UI_COMMON_DIRTY_POLICY.render, 'selected', 'tone', 'parts', 'onPress', 'onRemove'] }, fields: CHIP_FIELD_DEFINITIONS, normalize: schema => normalizeChipProps(schema.props), measureBounds: (_context, schema) => commonMeasureBounds(schema, normalizeChipProps) }; if (createNode) descriptor.createNode = createNode; return descriptor }
export const CHIP_NODE_DESCRIPTOR = createChipDescriptor()
